version: '3'

services:
  mongo:
    image: mongo
  api:
    container_name: book_review_api
    image: book_review_api:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongo:27017
      - MONGO_DATABASE_NAME=books
    ports:
      - '3000:3000'